name: Auto Pull Request

on:
  push:
    branches:
      - 'main'  # Only trigger when pushing to the main branch

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ github.ref }}
          title: "Auto PR for ${{ github.ref }}"
          body: "This PR was automatically created for branch ${{ github.ref }}"
