name: Rename game in Pr

on:
  pull_request:
    types: [opened, edited]

jobs:
  replace-phrase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set phrase pattern based on the target branch
      - name: Define Arguments
        run: |
            echo "PHRASE_PATTERN='CarletonSpades[ABCD]'" >> $GITHUB_ENV
            echo "REPLACEMENT_PHRASE='CarletonSpades'" >> $GITHUB_ENV

      - name: Run Game Renaming Script
        run: |
          chmod +x ./rename_game.sh  # Make sure your script is executable
          ./scripts/rename_game.sh "$PHRASE_PATTERN" "$REPLACEMENT_PHRASE"

      - name: Commit changes
        run: |
          git config --global user.name "${{ secrets.GH_USERNAME }}"  # Your GitHub username stored as a secret
          git config --global user.email "${{ secrets.GH_EMAIL }}"    # Your GitHub email stored as a secret
          
          # Check if there are changes to commit
          if ! git diff --exit-code; then
            git commit -am "Replace '$PHRASE_PATTERN' with '$REPLACEMENT_PHRASE' in code and filenames"
          else
            echo "No changes to commit."
          fi
          
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git push
